import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import { createRequire } from 'node:module';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';
import { CoreDatabase } from '../src/main/database.ts';
import { FeatureRuntimeStore } from '../src/main/features/feature-runtime-store.ts';
import { FeaturePackageManager } from '../src/main/features/package-manager.ts';
import { canonicalJson, packageFile, verifyOfficialPackage } from '../src/main/features/official-package.ts';
import { resolveProductPaths } from '../src/main/paths.ts';

const repository=path.resolve(import.meta.dirname,'..'); const require=createRequire(import.meta.url);
const worker=require(path.join(repository,'feature-packages/create-associate/source/middle/worker.cjs')) as any;
const cipher={encrypt:(value:string)=>`cipher:${value}`,decrypt:(value:string)=>value.replace(/^cipher:/u,'')};
const digest=(bytes:Buffer)=>crypto.createHash('sha256').update(bytes).digest('hex');
const xml=(value:string)=>value.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');

function combinationWorkbook(mask:number):Buffer{
  const rows:string[]=[]; let rowNumber=1; const row=(values:string[])=>`<row r="${rowNumber}">${values.map((value,index)=>`<c r="${String.fromCharCode(65+index)}${rowNumber}" t="inlineStr"><is><t>${xml(value)}</t></is></c>`).join('')}</row>`;
  const append=(headers:string[],values:string[])=>{rows.push(row(headers));rowNumber+=1;rows.push(row(values));rowNumber+=1;};
  if(mask&1)append(['系统ID','APP类型','System Risk Classification','Factors Considered','Omnia工作区'],['APP-COMBO','SAP ECC','Higher','组合校验','20100 APP']);
  if(mask&2)append(['数据库ID','DB 类型','Omnia工作区','关联系统ID'],['DB-COMBO','Oracle','20100 APP',mask&1?'APP-COMBO':'EXTERNAL-APP']);
  if(mask&4)append(['服务器ID','OS 类型','Omnia工作区','关联系统ID'],['OS-COMBO','WIN','20100 APP',mask&1?'APP-COMBO':'EXTERNAL-APP']);
  if(mask&8)append(['IT TOOL ID','Tool 类型','System Risk Classification','Omnia工作区'],['TOOL-COMBO','工单工具','Higher','20100 APP']);
  return worker.zip({'[Content_Types].xml':'<?xml version="1.0"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/></Types>','_rels/.rels':'<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>','xl/workbook.xml':'<?xml version="1.0"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Input" sheetId="1" r:id="rId1"/></sheets></workbook>','xl/_rels/workbook.xml.rels':'<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/></Relationships>','xl/worksheets/sheet1.xml':`<?xml version="1.0"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData>${rows.join('')}</sheetData></worksheet>`});
}

test('all 15 non-empty combinations parse, while external APP references and Tool Return fail closed locally',()=>{
  const legacy=verifyOfficialPackage(JSON.parse(fs.readFileSync(path.join(repository,'feature-packages/create-associate/candidates/create-associate-0.1.0.ofp'),'utf8')),'omnia-feature');
  const governance=JSON.parse(packageFile(legacy,'backend/governance.json').toString('utf8'));const dataDeclaration=governance.fields.find((field:any)=>field.fieldId==='P1.APP.IT.IS_DATA_AVAILABLE');Object.assign(dataDeclaration,{defaultRuleId:'v4.app-is-data-available-false.v1',defaultValue:false});governance.derivationRules.push({ruleId:'v4.app-is-data-available-false.v1',targetFieldId:dataDeclaration.fieldId,algorithm:'constant_boolean_false',constantValue:false,sourceTraceId:'v4:phase1:application:isDataAvailable=false'});governance.derivationRules.push({ruleId:'v4.phase1-gra-name-from-element-id.v1',targetFieldId:'P1.RUNTIME.GRA.NAME',dependencyFieldId:'P1.RUNTIME.IT.ELEMENT_ID',algorithm:'prefix_literal',prefix:'GRA-',sourceTraceId:'v4:omnia-phase1.js:716'});
  for(let mask=1;mask<16;mask+=1){const parsed=worker.parseUserWorkbook(combinationWorkbook(mask),`combo-${mask}`,governance);worker.recomputeLocalIssues(parsed);const kinds=new Set(parsed.rows.map((row:any)=>row.kind));for(const [bit,kind] of [[1,'APP'],[2,'DB'],[4,'OS'],[8,'TOOL']] as const)assert.equal(kinds.has(kind),Boolean(mask&bit),`mask ${mask} ${kind}`);assert.equal(parsed.issues.some((issue:any)=>/区段.*缺少|必须.*(?:APP|DB|OS|Tool).*区段/u.test(issue.message)),false,`mask ${mask}`);const blockers=parsed.issues.filter((issue:any)=>issue.state==='needs_input'||issue.state==='blocking');const mustBlock=Boolean(mask&8)||Boolean((mask&6)&&!(mask&1));assert.equal(blockers.length>0,mustBlock,`mask ${mask}: ${JSON.stringify(parsed.issues)}`);if(mask&8)assert.ok(blockers.some((issue:any)=>issue.code==='UNSUPPORTED.TOOL_RETURN'));if((mask&6)&&!(mask&1))assert.ok(blockers.some((issue:any)=>issue.code==='UNSUPPORTED.EXTERNAL_APP_REFERENCE'));}
});

test('0.2.1 package carries the exact signed V3 source template, three user steps and corrective Review actions',()=>{
  const packagePath=path.join(repository,'feature-packages/create-associate/candidates/create-associate-0.2.1.ofp'); const envelope=verifyOfficialPackage(JSON.parse(fs.readFileSync(packagePath,'utf8')),'omnia-feature');
  const manifest=JSON.parse(packageFile(envelope,'manifest.json').toString('utf8')); const surface=JSON.parse(packageFile(envelope,'frontend/surface.json').toString('utf8')); const template=packageFile(envelope,'backend/Phase1-用户填写模板V3.xlsx'); const source=fs.readFileSync(path.join(repository,'source_files','Phase1-用户填写模板V3.xlsx'));
  assert.equal(manifest.version,'0.2.2');assert.equal(manifest.sequence,4);assert.equal(manifest.minimumShellVersion,'0.4.8');assert.deepEqual(manifest.navigation.groups,[]);assert.equal(manifest.navigation.leaves[0].parentId,'');assert.deepEqual(surface.workflow.steps.map((step:any)=>step.label),['上传资料','校验','回传']);assert.equal(surface.actions.find((action:any)=>action.actionId==='download-source-template').output.memberPath,'backend/Phase1-用户填写模板V3.xlsx');assert.deepEqual(['apply-revisions','remove-batch-row','revalidate-all','back-to-upload','restart-run'].map((id)=>surface.actions.find((action:any)=>action.actionId===id)?.actionId),['apply-revisions','remove-batch-row','revalidate-all','back-to-upload','restart-run']);assert.equal(surface.actions.find((action:any)=>action.actionId==='restart-run').presentation,'restart');assert.equal(digest(template),digest(source));assert.equal(manifest.assets.find((asset:any)=>asset.kind==='source_template').sha256,digest(source));
});

test('existing data upgrades in place and picker/drop share the same managed import chain without touching binding or old Run',()=>{
  const root=fs.mkdtempSync(path.join(os.tmpdir(),'omnia-v5-in-place-upgrade-'));const paths=resolveProductPaths(root);const database=new CoreDatabase(paths.database,cipher);const manager=new FeaturePackageManager(database.db,paths); const oldPackage=path.join(repository,'feature-packages/create-associate/candidates/create-associate-0.1.0.ofp'),nextPackage=path.join(repository,'feature-packages/create-associate/candidates/create-associate-0.2.1.ofp');const timestamp=new Date().toISOString(),oldRun=crypto.randomUUID();
  try{
    manager.install(oldPackage); database.db.prepare(`UPDATE remote_binding_settings SET pair_id='pair-existing',connector_id='connector-existing',generation=7,token_ciphertext='cipher:token-existing',lifecycle='bound' WHERE singleton=1`).run(); database.db.prepare(`INSERT INTO feature_runs(run_id,trace_id,feature_id,feature_version,engagement_id,state,state_revision,source_artifact_id,template_version_id,output_artifact_id,plan_digest,last_error,created_at,updated_at) VALUES(?,?,'omnia.create-associate','0.1.0','engagement-existing','succeeded',9,'','','','','',?,?)`).run(oldRun,crypto.randomUUID(),timestamp,timestamp);
    manager.install(nextPackage); const binding=database.db.prepare(`SELECT pair_id,connector_id,generation,token_ciphertext FROM remote_binding_settings WHERE singleton=1`).get() as any;assert.deepEqual({...binding},{pair_id:'pair-existing',connector_id:'connector-existing',generation:7,token_ciphertext:'cipher:token-existing'});assert.equal((database.db.prepare(`SELECT state FROM feature_runs WHERE run_id=?`).get(oldRun) as any).state,'succeeded');const exported=manager.exportManagedAsset('omnia.create-associate','0.2.1','download-source-template','backend/Phase1-用户填写模板V3.xlsx');assert.equal(exported.suggestedName,'Phase1-用户填写模板V3.xlsx');assert.equal(digest(fs.readFileSync(exported.source)),digest(fs.readFileSync(path.join(repository,'source_files','Phase1-用户填写模板V3.xlsx'))));
    const before=(database.db.prepare(`SELECT COUNT(*) AS count FROM feature_runs`).get() as any).count;assert.equal((database.db.prepare(`SELECT COUNT(*) AS count FROM feature_runs`).get() as any).count,before,'cancelled picker creates no Run because no import method is called');
    const bytes=combinationWorkbook(1);const request={featureId:'omnia.create-associate',featureVersion:'0.2.1',surfaceId:'create-associate.workbench',actionId:'import-source-workbook',accept:['.xlsx']};const selected=path.join(root,'selected.xlsx');fs.writeFileSync(selected,bytes);const picker=manager.importArtifact(request,selected);const dropped=manager.importArtifactBytes(request,'dropped.xlsx',new Uint8Array(bytes));assert.equal(picker.sha256,dropped.sha256);assert.notEqual(picker.runId,dropped.runId);const refs=database.db.prepare(`SELECT source_ref FROM feature_artifacts WHERE artifact_id IN (?,?) ORDER BY source_ref`).all(picker.artifactId,dropped.artifactId) as any[];assert.deepEqual(refs.map((row)=>row.source_ref),['interactive-file-picker','renderer-drag-drop']);
  }finally{database.close();fs.rmSync(root,{recursive:true,force:true});}
});

test('bootstrap capability evidence is written only after every command has verified readback and is scope exact',()=>{
  const root=fs.mkdtempSync(path.join(os.tmpdir(),'omnia-v5-bootstrap-evidence-'));const paths=resolveProductPaths(root);const database=new CoreDatabase(paths.database,cipher);const store=new FeatureRuntimeStore(database.db,paths);
  const context={featureId:'omnia.create-associate',featureVersion:'0.2.1',allowMutation:true}; const runId=crypto.randomUUID(),intentId=crypto.randomUUID(),commandId=crypto.randomUUID(),receiptId=crypto.randomUUID(),now=new Date().toISOString(); const engagementId='11111111-1111-4111-8111-111111111111',workspaceId='22222222-2222-4222-8222-222222222222';const binding={connectorId:'connector-1',sessionGeneration:1,engagementId,authorityInstanceId:'authority-1',tenantOrOrgId:'tenant-1',packId:'pack-1'};const safetyLock={enabled:true,engagementId,workspaceIds:[workspaceId]};
  try{
    database.db.prepare(`INSERT INTO feature_runs(run_id,trace_id,feature_id,feature_version,engagement_id,state,state_revision,source_artifact_id,template_version_id,output_artifact_id,plan_digest,last_error,created_at,updated_at) VALUES(?,?,'omnia.create-associate','0.2.1',?,'returning',3,'','','',?,'',?,?)`).run(runId,crypto.randomUUID(),engagementId,'a'.repeat(64),now,now);
    database.db.prepare(`INSERT INTO feature_confirmations(confirmation_id,run_id,message_id,plan_digest,connector_id,session_generation,engagement_id,authority_instance_id,tenant_or_org_id,pack_id,safety_revision,credential_digest,preflight_digest,confirmation_token_digest,decision,actor_id,decision_at,consumed_command_id,expires_at,created_at) VALUES(?,?,?,?,?,1,?,?,?,?,1,?,?,?,'approved','local-user',?,'',?,?)`).run(crypto.randomUUID(),runId,`return:${runId}`,'a'.repeat(64),binding.connectorId,engagementId,binding.authorityInstanceId,binding.tenantOrOrgId,binding.packId,'b'.repeat(64),'c'.repeat(64),'d'.repeat(64),now,'2099-01-01T00:00:00.000Z',now);
    database.db.prepare(`INSERT INTO managed_content_intents(intent_id,run_id,plan_digest,target_kind,target_key,intended_revision_json,state,created_at,updated_at) VALUES(?,?,?,'object','object|sap','{}','failed',?,?)`).run(intentId,runId,'a'.repeat(64),now,now);
    assert.throws(()=>store.call('recordBootstrapCapabilityEvidence',{runId,connectorBinding:binding,safetyLock},context),/incomplete/);assert.equal((database.db.prepare('SELECT COUNT(*) AS count FROM feature_capability_evidence').get() as any).count,0);
    database.db.prepare(`UPDATE managed_content_intents SET state='verified' WHERE intent_id=?`).run(intentId);
    database.db.prepare(`INSERT INTO feature_commands(command_id,run_id,intent_id,operation_id,idempotency_key,plan_digest,request_digest,evidence_operation_ids_json,evidence_target_identity_key,evidence_request_digest,state,commit_point_at,submitted_at,completed_at,last_error,created_at) VALUES(?,?,?,?,?,?,?,'[]','','','readback_verified',?,?,?,'',?)`).run(commandId,runId,intentId,'omnia.create-associate.object.create.v1','e'.repeat(64),'a'.repeat(64),'f'.repeat(64),now,now,now,now);
    database.db.prepare(`INSERT INTO feature_operation_receipts(receipt_id,run_id,command_id,feature_id,feature_version,operation_package_digest,operation_id,authority_digest,connector_id,session_generation,engagement_id,authority_instance_id,tenant_or_org_id,pack_id,frozen_target_key,target_identity_key,workspace_ids_json,plan_digest,request_digest,response_digest,response_json,created_at) VALUES(?,?,?,?,?,?,?,?,?,1,?,?,?,?,?,?,?,?,?,?,?,?)`).run(receiptId,runId,commandId,context.featureId,context.featureVersion,`sha256:${'1'.repeat(64)}`,'omnia.create-associate.object.reconcile.v1','2'.repeat(64),binding.connectorId,engagementId,binding.authorityInstanceId,binding.tenantOrOrgId,binding.packId,'object|sap','target-sap',canonicalJson([workspaceId]),'a'.repeat(64),'3'.repeat(64),'4'.repeat(64),'{}',now);
    database.db.prepare(`INSERT INTO feature_command_evidence(evidence_id,command_id,run_id,evidence_type,evidence_digest,receipt_id,verified,payload_json,occurred_at) VALUES(?,?,?,'readback',?,?,1,'{}',?)`).run(crypto.randomUUID(),commandId,runId,'5'.repeat(64),receiptId,now);
    const result=store.call('recordBootstrapCapabilityEvidence',{runId,connectorBinding:binding,safetyLock},context) as any;assert.equal(result.recorded,true);
    assert.equal((store.call('getCapabilityEvidenceState',{scenarioId:'create-associate-return-v1',capabilityId:'phase1-full-return-v1',connectorBinding:binding,workspaceIds:[workspaceId]}, {...context,allowMutation:false}) as any).verified,true);
    assert.equal((store.call('getCapabilityEvidenceState',{scenarioId:'create-associate-return-v1',capabilityId:'phase1-full-return-v1',connectorBinding:{...binding,packId:'other-pack'},workspaceIds:[workspaceId]}, {...context,allowMutation:false}) as any).verified,false);
  }finally{database.close();fs.rmSync(root,{recursive:true,force:true});}
});
